create table if not exists goal_activity (
    id bigint generated by default as identity,
    user_id bigint not null,
    goal_id bigint not null,
    activity_date date not null,
    note text,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_goal_activity_user foreign key (user_id) references app_user(id),
    constraint fk_goal_activity_goal foreign key (goal_id) references goal_item(id) on delete cascade,
    constraint uk_goal_activity_goal_date unique (goal_id, activity_date)
);

create index if not exists idx_goal_activity_user_date on goal_activity(user_id, activity_date);
create index if not exists idx_goal_activity_goal_date on goal_activity(goal_id, activity_date);
