alter table mindvault_learning_item
    add column learning_type varchar(50) not null default 'IMPORTANT_TOPIC';

alter table mindvault_learning_item
    add column source_label varchar(255);

alter table mindvault_learning_item
    add column review_enabled boolean not null default true;

alter table mindvault_learning_item
    add column lapse_count integer not null default 0;

alter table mindvault_learning_item
    add column importance integer not null default 3;

update mindvault_learning_item
set learning_type = 'RANDOM_LEARNING'
where source = 'RANDOM';

update mindvault_learning_item
set importance = priority
where importance = 3 and priority is not null;

create table mindvault_resource (
    id bigint generated by default as identity,
    user_id bigint not null,
    item_id bigint not null,
    resource_type varchar(50) not null,
    title varchar(255) not null,
    description text,
    url text,
    storage_path varchar(1024),
    mime_type varchar(255),
    size_bytes bigint,
    original_file_name varchar(512),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint fk_mindvault_resource_user foreign key (user_id) references app_user(id),
    constraint fk_mindvault_resource_item foreign key (item_id) references mindvault_learning_item(id)
);

create index idx_mindvault_resource_user on mindvault_resource(user_id);
create index idx_mindvault_resource_item on mindvault_resource(item_id);
